import { create } from 'storybook/theming';

const fontBase = '"Inter", system-ui, sans-serif';

export const auiLight = create({
    base: 'light',
    brandTitle: 'Ensi Admin-UI',
    brandUrl: 'https://ensi.tech',
    brandImage: '/logo-light.svg',
    brandTarget: '_self',
    fontBase,
    colorPrimary: '#3d3d3d',
    colorSecondary: '#3d3d3d',
    appBg: '#ffffff',
    appContentBg: '#ffffff',
    appPreviewBg: '#ffffff',
    appBorderColor: '#d1d1d1',
    appBorderRadius: 8,
    textColor: '#1b1d22',
    textMutedColor: '#888888',
    barBg: '#ffffff',
    barTextColor: '#888888',
    barSelectedColor: '#3d3d3d',
    barHoverColor: '#2e2e2e',
    inputBg: '#ffffff',
    inputBorder: '#d1d1d1',
    inputTextColor: '#1b1d22',
    inputBorderRadius: 8,
});

export const auiDark = create({
    base: 'dark',
    brandTitle: 'Ensi Admin-UI',
    brandUrl: 'https://ensi.tech',
    brandImage: '/logo-dark.svg',
    brandTarget: '_self',
    fontBase,
    colorPrimary: '#f0f2f4',
    colorSecondary: '#888888',
    appBg: '#1b1d22',
    appContentBg: '#232526',
    appPreviewBg: '#1b1d22',
    appBorderColor: '#3f4248',
    appBorderRadius: 8,
    textColor: '#f0f2f4',
    textMutedColor: '#888888',
    barBg: '#232526',
    barTextColor: '#888888',
    barSelectedColor: '#888888',
    barHoverColor: '#ffffff',
    inputBg: '#232526',
    inputBorder: '#3f4248',
    inputTextColor: '#f0f2f4',
    inputBorderRadius: 8,
});
