import { create } from 'storybook/theming';

export const auiLight = create({
    base: 'light',
    brandTitle: 'admin-ui-base',
    brandUrl: 'https://ensi.tech',
    brandTarget: '_self',
    colorPrimary: '#00bea2',
    colorSecondary: '#00bea2',
    appBg: '#fafafa',
    appContentBg: '#ffffff',
    appPreviewBg: '#fafafa',
    appBorderColor: '#d8dce2',
    appBorderRadius: 8,
    textColor: '#1b1d22',
    textMutedColor: '#55585e',
    barBg: '#ffffff',
    barTextColor: '#55585e',
    barSelectedColor: '#00bea2',
    barHoverColor: '#00a88f',
    inputBg: '#ffffff',
    inputBorder: '#d8dce2',
    inputTextColor: '#1b1d22',
    inputBorderRadius: 8,
});

export const auiDark = create({
    base: 'dark',
    brandTitle: 'admin-ui-base',
    brandUrl: 'https://ensi.tech',
    brandTarget: '_self',
    colorPrimary: '#00bea2',
    colorSecondary: '#00bea2',
    appBg: '#1b1d22',
    appContentBg: '#232526',
    appPreviewBg: '#1b1d22',
    appBorderColor: '#3f4248',
    appBorderRadius: 8,
    textColor: '#f0f2f4',
    textMutedColor: '#949aa6',
    barBg: '#232526',
    barTextColor: '#949aa6',
    barSelectedColor: '#00bea2',
    barHoverColor: '#00a88f',
    inputBg: '#232526',
    inputBorder: '#3f4248',
    inputTextColor: '#f0f2f4',
    inputBorderRadius: 8,
});
